class Character{
    constructor(token, talents) {
        this.token = token;
        this.weapons = [];
        this.availabletalents = {
            "adamantiumfaith": false,
            "aegisofcontempt": false,
            "ambassadorimp": false,
            "ambidexterous": false,
            "archivator": false,
            "armormonger": false,
            "assassinstrike": false,
            "bastionironwill": false,
            "battlerage": false,
            "blademaster": false,
            "blindfighting": false,
            "bodyguard": false,
            "bulgingbiceps": false,
            "bulwarkoffaith": false,
            "catfall": false,
            "cluesfromcrowds": false,
            "combatmaster": false,
            "constantvigilance": false,
            "contact network": false,
            "coordinatedinterrogation": false,
            "counterattack": false,
            "coverup": false,
            "crushingblow": false,
            "daemonhunter": false,
            "daemonicdisrupt": false,
            "daemonologist": false,
            "darksoul": false,
            "deathdealer": false,
            "delicateinterrogation": false,
            "denythewitch": false,
            "devastatingassault": false,
            "diehard": false,
            "disarm": false,
            "divineprotection": false,
            "doubletap": false,
            "doudbleteam": false,
            "enemy": false,
            "eyeofvengeance": false,
            "faceinacrowd": false,
            "favoredbywarp": false,
            "ferricsummons": false,
            "fieldvivi": false,
            "flagellant": false,
            "flashofinsight": false,
            "frenzy": false,
            "grenadier": false,
            "haloofcommand": false,
            "hammerblow": false,
            "hardenedsoul": false,
            "hardtarget": false,
            "hardy": false,
            "hatred": false,
            "hipshooting": false,
            "hotshotpilot": false,
            "hulldown": false,
            "independenttargeting": false,
            "indomitableconv": false,
            "inescapableattack": false,
            "infusedknowledge": false,
            "inspiringaura": false,
            "instrumentofhiswill": false,
            "intothejaws": false,
            "ironfaith": false,
            "ironjaw": false,
            "ironresolve": false,
            "jaded": false,
            "keenintuition": false,
            "killingstrike": false,
            "leapingdodge": false,
            "leapup": false,
            "lightningattack": false,
            "luminenblast": false,
            "luminenshock": false,
            "maglevtrans": false,
            "marksman": false,
            "mastery": false,
            "mechadendrite": false,
            "mightyshot": false,
            "mountedwarrior": false,
            "neverdie": false,
            "nowheretohide": false,
            "oneonone": false,
            "peer": false,
            "penitentpsy": false,
            "precisionkiller": false,
            "preturnaturalspeed": false,
            "prosanguine": false,
            "purityofhatred": false,
            "pushthelimit": false,
            "quickdraw": false,
            "rapidreload": false,
            "resistance": false,
            "riteofbanish": false,
            "sancticpurity": false,
            "shieldwall": false,
            "skilledrider": false,
            "soundcon": false,
            "sprint": false,
            "stepaside": false,
            "strongminded": false,
            "superiorchi": false,
            "swiftattack": false,
            "taintedpsy": false,
            "takedown": false,
            "targetselection": false,
            "technicalknock": false,
            "thundercharge": false,
            "truegrit": false,
            "twowpnmstr": false,
            "twowpnwld": false,
            "unarmedspec": false,
            "warpconduit": false,
            "warplock": false,
            "warpsense": false,
            "weaponintuition": false,
            "weapontech": false,
            "whirlwindofdeath": false,
            "witchfinder": false,
            "xenosavant": false,
            "amorphous": false,                 //traits
            "amphibious": false,
            "autostabilized": false,
            "banefulpres": -1,
            "bestial": false,
            "blind": false,
            "brutalcharge": -1,
            "burrower": -1,
            "cranialcircuitry": false,
            "crawler": false,
            "cybermantle": false,
            "daemonic": -1,
            "darksight": false,
            "deadlynatural": false,
            "electrograft": false,
            "electooinductors": false,
            "fear": -1,
            "flyer": -1,
            "frombeyond": false,
            "hoverer": -1,
            "incorporeal": false,
            "machine": -1,
            "mindlock": false,
            "multiplearms": -1,
            "naturalarmor": -1,
            "naturalweapons": false,
            "potentiacoil": false,
            "phase": false,
            "psyker": false,
            "quadruped": false,
            "regeneration": -1,
            "sanctioned": false,
            "size": -1,
            "sonarsense": false,
            "soulbound": false,
            "stampede": false,
            "stuffofnightmares": false,
            "sturdy": false,
            "touchedbythefates": -1,
            "toxic": -1,
            "undying": false,
            "unnaturalsenses": false,
            "warpinstability": false,
            "warpweapons": false,
            "abyssalterror": false,                 //Elite Advances
            "adrenalrecovery": false,
            "advancedbattlesuittraining": false,
            "allyofthexenos": false,
            "apotheosisdelayed": false,
            "attackmytarget": false,
            "baneofthedaemon": false,
            "battlefieldtechnician": false,
            "bestofthebest": false,
            "blessedmartyrdom": false,
            "blessingoftheethereals": false,
            "bondingritual": false,
            "boundtothehighest": false,
            "braceforimpact": false,
            "burytheknife": false,
            "ceaselesscrusader": false,
            "cleanseandpurify": false,
            "cleansewithfire": false,
            "cogswithincogs": false,
            "coldreading": false,
            "coldtrader": false,
            "combatflair": false,
            "completecontrol": false,
            "corruptedcharge": false,
            "coverandadvance": false,
            "daemonicaffinity": false,
            "daemonicanathema": false,
            "daemonicdomination": false,
            "daemonicemergence": false,
            "damagecontrol": false,
            "despoiler": false,
            "discipleofkauyon": false,
            "discipleofmontka": false,
            "dispassionatedispatch": false,
            "divineministration": false,
            "divinesymbol": false,
            "divinevengeance": false,
            "emperorsguidance": false,
            "envoyofthegreatergood": false,
            "exemplaroftheselflesscause": false,
            "fated": false,
            "favoreditem": false,
            "feelnopain": false,
            "firebrandscall": false,
            "firesupport": false,
            "flamesoffaith": false,
            "fleshwarp": false,
            "furiousfusillade": false,
            "furiouszeal": false,
            "greaterthanthesun": false,
            "holdfast": false,
            "honorguard": false,
            "hunkerdown": false,
            "inspiredintuition": false,
            "jackofalltrades": false,
            "killerseye": false,
            "legendary": false,
            "legendaryarmament": false,
            "lostokenhancement": false,
            "luminenbarrier": false,
            "luminendesecration": false,
            "luminenflare": false,
            "luminenshield": false,
            "luminensurge": false,
            "marauder": false,
            "martyrsgift": false,
            "masterofalltrades": false,
            "masteroftechnology": false,
            "metalfatigue": false,
            "mightoftheemperor": false,
            "mindsight": false,
            "mindtrap": false,
            "mortalglamour": false,
            "newallies": false,
            "nullfield": false,
            "operativeconditioning": false,
            "panxenoist": false,
            "personalequipment": false,
            "priorityfire": false,
            "psychicnull": false,
            "purgetheunclean": false,
            "renownedwarrant": false,
            "resurrection": false,
            "riteofawe": false,
            "riteoffear": false,
            "riteofpurethought": false,
            "secondsight": false,
            "sharedestiny": false,
            "shieldingfaith": false,
            "shieldofcontempt": false,
            "shipmaster": false,
            "snapshot": false,
            "soullessaura": false,
            "soulstorm": false,
            "soulward": false,
            "spiritofthemartyr": false,
            "squadmode": false,
            "strengththroughconviction": false,
            "strengththroughunity": false,
            "subversiveprogramming": false,
            "suffertheflesh": false,
            "superiorsupplychain": false,
            "supportingfire": false,
            "supremetelepath": false,
            "swarmprotocols": false,
            "tacticalflexibility": false,
            "tacticalwithdrawal": false,
            "takethemalive": false,
            "technologicalinsight": false,
            "technologytriumphant": false,
            "tempestofmonkua": false,
            "theemperorprotects": false,
            "thepowerbeyond": false,
            "thepowerwithin": false,
            "throughunitydevastation": false,
            "undyingwarrior": false,
            "unfalteringredemption": false,
            "unhalloweddiscovery": false,
            "unholyinsight": false,
            "unorthodoxrites": false,
            "veteran's reflexes": false,
            "voidsavant": false,
            "warpanathema": false,
            "warpawareness": false,
            "warpbane": false,
            "warpdisruption": false,
            "warpforge": false,
            "watchfulforbetrayal": false,
            "whispersfrombeyond": false,
            "whispersofsamadhi": false,
            "willoftheinquisitor": false,
            "wrathoftherighteous": false,
            "xenoarcheologist": false,
            "xenosaugmentation": false,
            "xenosfamiliarity": false,
            "xenoshybridization": false,
            "zealotspassion": false,
            "coldsoul": false,              //traits from EAs
            "lostokaugmentation": false,
            "masteryofaugurs": false,
            "masteryofgunnery": false,
            "masteryofsmallcraft": false,
            "masteryofspace": false,
            "possessed": false,
            "purefaith": false,
            "rigormentis": false,
            "temperament": false,
            "untouchable": false,
            "xenophilia": false
        };
        this.activetalents = talents;
    }

    
    addcustomweapon(single, semi, full, numdice, dmg, pen, special, quality, wpnname, type, ammo, mod1, mod2, mod3, effects, wpncat){
        var newweapon = {
            weaponname: wpnname,
            weapon: new Weapon(single, semi, full, numdice, dice, dmg, pen, special, quality, wpnname, type, ammo, mod1, mod2, mod3, effects, wpncat)
        };
        weapons.push(newweapon);
    }

    clearweapons(){
        this.weapons = [];
    }

    get token(){
        return this._range;
    }
    get activetalents(){
        return this._activetalents;
    }

    set token(value) {
        if (typeof value === 'undefined' || typeof value != 'string' ) throw "invalid token";
        else this._token = value;
      }
    set activetalents(value) {
        let i, j, sub, cur = 0;
        for (i = 0, j = value.length; i < j; i++) {
            value[i] = value[i].replace(/^\s+|\s+$/g, '');    //remove whitespace
            sub = value[i].match(/\d/);                              //find any numbers in parentheses
            value[i] = value[i].replace(/\(([^)]+)\)/g, '');  //remove parentheses and anything inside
            cur = value[i];                                          
            if(sub != null){                                                //if there was a number in parentheses, set the array location equal to that number, otherwise set it as true
                availabletalents[cur] = sub;
            } else {
                availabletalents[cur] = true;  
            }
        }
        this._activetalents = availabletalents.filter(function(currentvalue, index, arr){
            return (currentvalue[index]===true || (Number.isInteger(currentvalue[index]) && currentvalue[index]>-1 && currentvalue[index]<50));
        });
    }

}