/**Author: Argagarg
 * Source: https://github.com/Argagarg/RT2sheet
 * About: This module characterizes the 40k talents and contains methods for importing / looking up talents for character use
 **/
import {Talent} from "./talent.js";
export class Talents{
    constructor(talentStr, newTalents = null) {
        this.availableExisting = {
            "adamantiumfaith": false,
            "aegisofcontempt": false,
            "ambassadorimp": false,
            "ambidexterous": false,
            "archivator": false,
            "armormonger": false,
            "assassinstrike": false,
            "bastionironwill": false,
            "battlerage": false,
            "blademaster": false,
            "blindfighting": false,
            "bodyguard": false,
            "bulgingbiceps":                {name: 'BulgingBiceps',evalcondition: "skillname=='Athletics'",evaleffect: "",triggers: ['post'],description:"Grants +20 to the Heft use of the Athletics skill(NInc)"},
            "bulwarkoffaith": false,
            "catfall":                      {name: 'Catfall',evalcondition: "skillname=='Acrobatics'",evaleffect: "",triggers: ['post'],description:"Grants +20 to the Jump use of Acrobatics(NInc)"},
            "cluesfromcrowds": false,
            "combatmaster": false,
            "constantvigilance": false,
            "contact network": false,
            "coordinatedinterrogation":     {name: 'CoordinatedInterrogation',evalcondition: "skillname=='Interrogation'",evaleffect: "modifier += 10;",triggers: ['prebind','post'],description:"Grants +10 to all interrogation tests (Inc) and +5 for each additional ally with this talent(NInc)"},
            "counterattack": false,
            "coverup": false,
            "crushingblow": false,
            "daemonhunter": false,
            "daemonicdisrupt": false,
            "daemonologist": false,
            "darksoul": false,
            "deathdealer": false,
            "delicateinterrogation":        {name: 'DelicateInterrogation',evalcondition: "skillname=='Interrogation'",evaleffect: "",triggers: ['post'],description:"Subtlety loss from Interrogation reduced by 1d5 (min 1)(NInc)"},
            "denythewitch": false,
            "devastatingassault": false,
            "diehard": false,
            "disarm": false,
            "divineprotection": false,
            "doubletap": false,
            "doudbleteam": false,
            "enemy":                        {name: 'Enemy',evalcondition: "(skillname=='Charm'||skillname=='Deceive'||skillname=='Command'||skillname=='Inquiry')",evaleffect: "",triggers: ['post'],description:"-10 to interaction tests with the selected group(NInc)"},
            "eyeofvengeance": false,
            "faceinacrowd":                 {name: 'FaceinaCrowd',evalcondition: "skillname=='Stealth'",evaleffect: "",triggers: ['post'],description:"Can use Fellowship instead of Agility when using the Shadowing ability of the Stealth skill(NInc)"},
            "favoredbywarp": false,
            "ferricsummons": false,
            "fieldvivi": false,
            "flagellant": false,
            "flashofinsight": false,
            "frenzy": false,
            "grenadier": false,
            "haloofcommand":                {name: 'FaceinaCrowd',evalcondition: "(skillname=='Charm'||skillname=='Deceive'||skillname=='Command'||skillname=='Inquiry')",evaleffect: "",triggers: ['post'],description:"Can affect targets within 100 x FB meters rather than 10(NInc)"},
            "hammerblow": false,
            "hardenedsoul": false,
            "hardtarget": false,
            "hardy": false,
            "hatred": false,
            "hipshooting": false,
            "hotshotpilot": false,
            "hulldown": false,
            "independenttargeting": false,
            "indomitableconv": false,
            "inescapableattack": false,
            "infusedknowledge": false,
            "inspiringaura": false,
            "instrumentofhiswill": false,
            "intothejaws": false,
            "ironfaith": false,
            "ironjaw": false,
            "ironresolve": false,
            "jaded": false,
            "keenintuition": false,
            "killingstrike": false,
            "leapingdodge": false,
            "leapup": false,
            "lightningattack": false,
            "luminenblast": false,
            "luminenshock": false,
            "maglevtrans": false,
            "marksman": false,
            "mastery": false,
            "mechadendrite": false,
            "mightyshot": false,
            "mountedwarrior": false,
            "neverdie": false,
            "nowheretohide": false,
            "oneonone": false,
            "peer": false,
            "penitentpsy": false,
            "precisionkiller": false,
            "preturnaturalspeed": false,
            "prosanguine": false,
            "purityofhatred": false,
            "pushthelimit": false,
            "quickdraw": false,
            "rapidreload": false,
            "resistance": false,
            "riteofbanish": false,
            "sancticpurity": false,
            "shieldwall": false,
            "skilledrider": false,
            "soundcon": false,
            "sprint": false,
            "stepaside": false,
            "strongminded": false,
            "superiorchi":                      {name: 'SuperiorChirurgeon',evalcondition: "skillname=='Medicae'",evaleffect: "modifier += 20;",triggers: ['prebind','post'],description:"+20 to Medicae (Inc), ignores Heavily Damaged penalty(NInc), and suffers only a -10 for Critical Damage(NInc)"},
            "swiftattack": false,
            "taintedpsy": false,
            "takedown": false,
            "targetselection": false,
            "technicalknock": false,
            "thundercharge": false,
            "truegrit": false,
            "twowpnmstr": false,
            "twowpnwld": false,
            "unarmedspec": false,
            "warpconduit": false,
            "warplock": false,
            "warpsense": false,
            "weaponintuition": false,
            "weapontech": false,
            "whirlwindofdeath": false,
            "witchfinder": false,
            "xenosavant": false,
            "amorphous": false,                 //traits
            "amphibious": false,
            "autostabilized": false,
            "banefulpres": -1,
            "bestial": false,
            "blind": false,
            "brutalcharge": -1,
            "burrower": -1,
            "cranialcircuitry": false,
            "crawler": false,
            "cybermantle": false,
            "daemonic": -1,
            "darksight": false,
            "deadlynatural": false,
            "electrograft": false,
            "electooinductors": false,
            "fear": -1,
            "flyer": -1,
            "frombeyond": false,
            "hoverer": -1,
            "incorporeal": false,
            "machine": -1,
            "mindlock": false,
            "multiplearms": -1,
            "naturalarmor": -1,
            "naturalweapons": false,
            "potentiacoil": false,
            "phase": false,
            "psyker": false,
            "quadruped": false,
            "regeneration": -1,
            "sanctioned": false,
            "size": -1,
            "sonarsense": false,
            "soulbound": false,
            "stampede": false,
            "stuffofnightmares": false,
            "sturdy": false,
            "touchedbythefates": -1,
            "toxic": -1,
            "undying": false,
            "unnaturalsenses": false,
            "warpinstability": false,
            "warpweapons": false,
            "abyssalterror": false,                 //Elite Advances
            "adrenalrecovery": false,
            "advancedbattlesuittraining": false,
            "allyofthexenos": false,
            "apotheosisdelayed": false,
            "attackmytarget": false,
            "baneofthedaemon": false,
            "battlefieldtechnician": false,
            "bestofthebest": false,
            "blessedmartyrdom": false,
            "blessingoftheethereals": false,
            "bondingritual": false,
            "boundtothehighest": false,
            "braceforimpact": false,
            "burytheknife": false,
            "ceaselesscrusader": false,
            "cleanseandpurify": false,
            "cleansewithfire": false,
            "cogswithincogs": false,
            "coldreading": false,
            "coldtrader": false,
            "combatflair": false,
            "completecontrol": false,
            "corruptedcharge": false,
            "coverandadvance": false,
            "daemonicaffinity": false,
            "daemonicanathema": false,
            "daemonicdomination": false,
            "daemonicemergence": false,
            "damagecontrol": false,
            "despoiler": false,
            "discipleofkauyon": false,
            "discipleofmontka": false,
            "dispassionatedispatch": false,
            "divineministration": false,
            "divinesymbol": false,
            "divinevengeance": false,
            "emperorsguidance": false,
            "envoyofthegreatergood": false,
            "exemplaroftheselflesscause": false,
            "fated": false,
            "favoreditem": false,
            "feelnopain": false,
            "firebrandscall": false,
            "firesupport": false,
            "flamesoffaith": false,
            "fleshwarp": false,
            "furiousfusillade": false,
            "furiouszeal": false,
            "greaterthanthesun": false,
            "holdfast": false,
            "honorguard": false,
            "hunkerdown": false,
            "inspiredintuition": false,
            "jackofalltrades": false,
            "killerseye": false,
            "legendary": false,
            "legendaryarmament": false,
            "lostokenhancement": false,
            "luminenbarrier": false,
            "luminendesecration": false,
            "luminenflare": false,
            "luminenshield": false,
            "luminensurge": false,
            "marauder": false,
            "martyrsgift": false,
            "masterofalltrades": false,
            "masteroftechnology": false,
            "metalfatigue": false,
            "mightoftheemperor": false,
            "mindsight": false,
            "mindtrap": false,
            "mortalglamour": false,
            "newallies": false,
            "nullfield": false,
            "operativeconditioning": false,
            "panxenoist": false,
            "personalequipment": false,
            "priorityfire": false,
            "psychicnull": false,
            "purgetheunclean": false,
            "renownedwarrant": false,
            "resurrection": false,
            "riteofawe": false,
            "riteoffear": false,
            "riteofpurethought": false,
            "secondsight": false,
            "sharedestiny": false,
            "shieldingfaith": false,
            "shieldofcontempt": false,
            "shipmaster": false,
            "snapshot": false,
            "soullessaura": false,
            "soulstorm": false,
            "soulward": false,
            "spiritofthemartyr": false,
            "squadmode": false,
            "strengththroughconviction": false,
            "strengththroughunity": false,
            "subversiveprogramming": false,
            "suffertheflesh": false,
            "superiorsupplychain": false,
            "supportingfire": false,
            "supremetelepath": false,
            "swarmprotocols": false,
            "tacticalflexibility": false,
            "tacticalwithdrawal": false,
            "takethemalive": false,
            "technologicalinsight": false,
            "technologytriumphant": false,
            "tempestofmonkua": false,
            "theemperorprotects": false,
            "thepowerbeyond": false,
            "thepowerwithin": false,
            "throughunitydevastation": false,
            "undyingwarrior": false,
            "unfalteringredemption": false,
            "unhalloweddiscovery": false,
            "unholyinsight": false,
            "unorthodoxrites": false,
            "veteran's reflexes": false,
            "voidsavant": false,
            "warpanathema": false,
            "warpawareness": false,
            "warpbane": false,
            "warpdisruption": false,
            "warpforge": false,
            "watchfulforbetrayal": false,
            "whispersfrombeyond": false,
            "whispersofsamadhi": false,
            "willoftheinquisitor": false,
            "wrathoftherighteous": false,
            "xenoarcheologist": false,
            "xenosaugmentation": false,
            "xenosfamiliarity": false,
            "xenoshybridization": false,
            "zealotspassion": false,
            "coldsoul": false,              //traits from EAs
            "lostokaugmentation": false,
            "masteryofaugurs": false,
            "masteryofgunnery": false,
            "masteryofsmallcraft": false,
            "masteryofspace": false,
            "possessed": false,
            "purefaith": false,
            "rigormentis": false,
            "temperament": false,
            "untouchable": false,
            "xenophilia": false
        };   
        this.active = talentStr;
        this.newTalents = newTalents;
    }

    //getters
    get active(){
        return this._active;
    }

    //setters
    set active(value) {
        let i, j, num, name = 0;
        let active = [];
        value = value.split(".");
        for (i = 0, j = value.length; i < j; i++) {
            value[i] = value[i].replace(/^\s+|\s+$/g, '');    //remove whitespace
            num = value[i].match(/\d/);                              //find any numbers in parentheses
            value[i] = value[i].replace(/\(([^)]+)\)/g, '');  //remove parentheses and anything inside
            name = value[i];
            if(num && this.availableExisting[name] && this.availableExisting[name].magnitude) this.availableExisting[name].magnitude = num;                                   
            if(this.availableExisting[name]) active.push(this.availableExisting[name]);
        }
        this._active = active;
        log("active talents:");
        log(this.active);
    }

}